"""Pygame entry point: window, default maze, and game loop.

Defaults are picked per maze type. Orthogonal: 20×20 grid, ~28px cells —
the same band the iOS reference app's "medium" preset uses. Sigma: 11×10
grid at 26px so the hex bounding box lands in a similar window footprint
without becoming uncomfortably tall (sqrt(3) ≈ 1.73 makes hex windows
naturally taller than square ones).

CLI:
    python -m mazer                     # default Orthogonal
    python -m mazer --type sigma        # hexagonal grid
    python -m mazer --type sigma --width 13 --height 11 --algo HuntAndKill

Movement input (works for every maze type):
    Single arrow keys → cardinal direction (UP/DOWN/LEFT/RIGHT).
    Held arrow chords → diagonal direction:
        ↑ + →  → UPPER_RIGHT
        ↑ + ←  → UPPER_LEFT
        ↓ + →  → LOWER_RIGHT
        ↓ + ←  → LOWER_LEFT
    Left mouse button on an *adjacent linked* cell → move there (single
    tap). Click-and-drag across the grid → chains moves cell-by-cell as
    the cursor crosses open walls (continuous trackpad/mouse navigation).

    The Rust ``make_move`` has built-in fallback for every direction
    (e.g. UPPER_RIGHT tries UpperRight → Up → Right), so chords work
    naturally on orthogonal too — pressing ↑+→ moves up if available,
    else right. Same forgiving feel as the iOS app's eight-way controls.

Sigma also keeps the legacy "hex roguelike" key layout for muscle memory:
    W                UP             Q                UPPER_LEFT
    X                DOWN           E                UPPER_RIGHT
                                    Z                LOWER_LEFT
                                    C                LOWER_RIGHT

Common keys:
    H                Toggle heatmap overlay
    S                Toggle solution-path overlay
    R / N            Regenerate with the current request (same params)
    M                Open settings menu (change type, algorithm, size)
    Esc              Quit (or close menu if menu is open).

Open-exit dots: the active cell shows small white dots near each open
edge — affordance equivalent to the iOS D-pad's per-direction enabled
state. If a key seems "not to move you", check the dots.
"""

from __future__ import annotations

import argparse
import math

import pygame

from mazer.maze import Cell, Maze, MazeGenerationError
from mazer.types import Algorithm, Coord, Direction, MazeRequest, MazeType
from mazer.ui.menu import MenuLayout, MenuState, draw_menu
from mazer.ui.renderer import (
    OFF_WHITE,
    generate_gradient,
    make_renderer,
)


HUD_HEIGHT = 56

# Minimum window size that ensures the settings menu panel (460 px wide,
# ~338 px tall + HUD) is fully visible.  Windows narrower or shorter than
# this are temporarily enlarged when the menu opens and restored on close.
_MENU_MIN_WINDOW_W = 500
_MENU_MIN_WINDOW_H = 450

# Key-repeat settings for gameplay movement.  A KEYDOWN event for a key
# that is already held is a repeat (generated by pygame's set_repeat).
# Non-movement actions (H/S/R/M) are filtered to first-press only.
_GAMEPLAY_REPEAT_DELAY = 200     # ms before first auto-move when key held
_GAMEPLAY_REPEAT_INTERVAL = 100  # ms between subsequent auto-moves

# Per-maze-type defaults. Tuple of (cell_size, width, height) — the
# default algorithm is RecursiveBacktracker for all types because it
# produces winding paths that show off the heatmap and solution-path
# overlays well; user can override with --algo.
_DEFAULTS: dict[MazeType, tuple[int, int, int]] = {
    MazeType.ORTHOGONAL: (28, 20, 20),
    MazeType.SIGMA: (26, 11, 10),
    MazeType.DELTA: (30, 20, 12),
}

ORTHOGONAL_KEYS: dict[int, Direction] = {
    pygame.K_UP: Direction.UP,
    pygame.K_DOWN: Direction.DOWN,
    pygame.K_LEFT: Direction.LEFT,
    pygame.K_RIGHT: Direction.RIGHT,
}

# Sigma uses the standard hex roguelike layout: W/Q/E across the top row
# of letters and Z/X/C across the bottom row, with the grid pivot point
# (S/D in QWERTY) deliberately *unbound* so a typo in either row never
# silently wraps. ↑ and ↓ also map to UP/DOWN as a common-sense affordance.
SIGMA_KEYS: dict[int, Direction] = {
    pygame.K_UP: Direction.UP,
    pygame.K_w: Direction.UP,
    pygame.K_DOWN: Direction.DOWN,
    pygame.K_x: Direction.DOWN,
    pygame.K_q: Direction.UPPER_LEFT,
    pygame.K_e: Direction.UPPER_RIGHT,
    pygame.K_z: Direction.LOWER_LEFT,
    pygame.K_c: Direction.LOWER_RIGHT,
}

# Delta uses the same six-direction layout as Sigma. The Rust make_move
# fallback resolves each direction to the correct triangle edge for the
# current cell orientation (Normal vs Inverted).
DELTA_KEYS: dict[int, Direction] = SIGMA_KEYS

_KEYS_BY_TYPE: dict[MazeType, dict[int, Direction]] = {
    MazeType.ORTHOGONAL: ORTHOGONAL_KEYS,
    MazeType.SIGMA: SIGMA_KEYS,
    MazeType.DELTA: DELTA_KEYS,
}

ARROW_KEYS: tuple[int, ...] = (pygame.K_UP, pygame.K_DOWN, pygame.K_LEFT, pygame.K_RIGHT)

_HUD_HINT_BY_TYPE: dict[MazeType, str] = {
    MazeType.ORTHOGONAL: "arrows + chords + drag/click",
    MazeType.SIGMA: "chords / W·Q·E·Z·X·C / drag/click",
    MazeType.DELTA: "chords / W·Q·E·Z·X·C / drag/click",
}


def _resolve_chord(up: bool, down: bool, left: bool, right: bool) -> Direction | None:
    """Resolve held arrow keys to a single Direction.

    Diagonal combinations win over cardinals. Opposing pairs (UP+DOWN,
    LEFT+RIGHT) cancel out — they're treated as if the perpendicular axis
    isn't held, so e.g. UP+DOWN+RIGHT resolves to RIGHT.

    Returns ``None`` if no arrow is held (callers shouldn't reach this
    case on KEYDOWN — defensive only).
    """
    vertical = up ^ down  # cancel if both
    horizontal = left ^ right
    if vertical and horizontal:
        if up and right:
            return Direction.UPPER_RIGHT
        if up and left:
            return Direction.UPPER_LEFT
        if down and right:
            return Direction.LOWER_RIGHT
        if down and left:
            return Direction.LOWER_LEFT
    if vertical:
        return Direction.UP if up else Direction.DOWN
    if horizontal:
        return Direction.LEFT if left else Direction.RIGHT
    return None


# Orthogonal: eight 45° sectors.  Angle 0° = rightward (+x), clockwise
# (y-down screen coords).  Each sector boundary is at multiples of 45°
# offset by 22.5° so the cardinal and diagonal centres are equidistant.
# Diagonals are passed straight to the Rust ``make_move`` which tries the
# vertical component first, then the horizontal — e.g. UPPER_RIGHT tries
# Up → Right — giving the liberal fallback the user feels on the trackpad.
_ORTHO_SECTOR_DIRECTIONS = (
    Direction.RIGHT,        # sector 0: 337.5°–22.5°
    Direction.LOWER_RIGHT,  # sector 1: 22.5°–67.5°
    Direction.DOWN,         # sector 2: 67.5°–112.5°
    Direction.LOWER_LEFT,   # sector 3: 112.5°–157.5°
    Direction.LEFT,         # sector 4: 157.5°–202.5°
    Direction.UPPER_LEFT,   # sector 5: 202.5°–247.5°
    Direction.UP,           # sector 6: 247.5°–292.5°
    Direction.UPPER_RIGHT,  # sector 7: 292.5°–337.5°
)

# Sigma: six 60° sectors mapped to hex directions, indexed by
# ``int((angle_degrees + 30) % 360 / 60)``.  Angle 0° = rightward (screen
# x+), increasing clockwise (y-down screen coords).  Centers per sector:
# 330° UPPER_RIGHT, 30° LOWER_RIGHT, 90° DOWN, 150° LOWER_LEFT,
# 210° UPPER_LEFT, 270° UP.
_SIGMA_SECTOR_DIRECTIONS = (
    Direction.UPPER_RIGHT,  # sector 0: 300°–360° / 0°–30°
    Direction.LOWER_RIGHT,  # sector 1: 30°–90°
    Direction.DOWN,         # sector 2: 90°–150°
    Direction.LOWER_LEFT,   # sector 3: 150°–210°
    Direction.UPPER_LEFT,   # sector 4: 210°–270°
    Direction.UP,           # sector 5: 270°–330°
)


def _direction_from_vector(dx: float, dy: float, maze_type: MazeType) -> Direction | None:
    """Resolve a drag vector to a Direction based on maze type.

    Orthogonal/Delta: angle mapped to nearest of 8 directions (45° sectors).
      Diagonal directions are passed to the Rust which applies per-type
      fallback — e.g. UPPER_RIGHT on a Normal delta cell tries UpperRight
      directly; on an Inverted cell the Rust resolves it to Up or Right.
    Sigma: angle mapped to nearest of 6 hex directions (60° sectors).
    Returns None for zero-length vectors or unimplemented maze types.
    """
    if dx == 0 and dy == 0:
        return None
    angle = (math.degrees(math.atan2(dy, dx)) + 360) % 360
    if maze_type in (MazeType.ORTHOGONAL, MazeType.DELTA):
        sector = int((angle + 22.5) / 45) % 8
        return _ORTHO_SECTOR_DIRECTIONS[sector]
    if maze_type == MazeType.SIGMA:
        sector = int((angle + 30) % 360 / 60)
        return _SIGMA_SECTOR_DIRECTIONS[sector]
    return None


class _DragState:
    """Swipe-to-move state machine.

    Click anywhere on the maze and hold.  As the cursor moves, the drag
    vector from the last-fired position is resolved to a direction; when
    it exceeds the threshold (``cell_size * 0.6``) a move fires and the
    anchor resets to the current position so the next move requires
    another threshold-worth of drag.  Works like a joystick — direction
    of travel determines movement, not which cell the cursor is on.
    """

    def __init__(self) -> None:
        self.active = False
        self._origin: tuple[int, int] | None = None

    def begin(self, pos: tuple[int, int]) -> None:
        """Start a drag session, recording the cursor anchor point."""
        self.active = True
        self._origin = pos

    def motion(
        self,
        pos: tuple[int, int],
        maze,
        cell_size: int,
        maze_type: MazeType,
    ) -> bool:
        """Handle MOUSEMOTION. Fires a move when the accumulated drag exceeds the threshold."""
        if not self.active or self._origin is None:
            return False
        ox, oy = self._origin
        dx = pos[0] - ox
        dy = pos[1] - oy
        if math.hypot(dx, dy) < cell_size * 0.6:
            return False
        direction = _direction_from_vector(dx, dy, maze_type)
        if direction is None:
            return False
        fired = maze.move(direction)
        self._origin = pos
        return fired

    def end(self) -> None:
        self.active = False
        self._origin = None


HUD_BG = OFF_WHITE
HUD_TITLE_COLOR = (40, 40, 40)
HUD_HINT_COLOR = (90, 90, 90)
SOLVED_TEXT_COLOR = (255, 255, 255)
SOLVED_OVERLAY_RGBA = (0, 0, 0, 130)


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(prog="python -m mazer", description="Mazer Pygame UI.")
    parser.add_argument(
        "--type",
        dest="maze_type",
        choices=[m.value.lower() for m in (MazeType.ORTHOGONAL, MazeType.SIGMA, MazeType.DELTA)],
        default=MazeType.ORTHOGONAL.value.lower(),
        help="Maze type: orthogonal (default), sigma (hex), or delta (triangular).",
    )
    parser.add_argument("--width", type=int, default=None, help="Grid width (cells). Default depends on type.")
    parser.add_argument("--height", type=int, default=None, help="Grid height (cells). Default depends on type.")
    parser.add_argument(
        "--algo",
        default=Algorithm.RECURSIVE_BACKTRACKER.value,
        help=f"Generation algorithm. Default {Algorithm.RECURSIVE_BACKTRACKER.value}.",
    )
    return parser.parse_args(argv)


def _build_request(args: argparse.Namespace) -> tuple[MazeRequest, int]:
    """Translate CLI args into a (request, cell_size) pair."""
    maze_type = MazeType(args.maze_type.capitalize())
    cell_size, default_w, default_h = _DEFAULTS[maze_type]
    width = args.width if args.width is not None else default_w
    height = args.height if args.height is not None else default_h
    algorithm = Algorithm(args.algo)
    request = MazeRequest(
        maze_type=maze_type,
        width=width,
        height=height,
        algorithm=algorithm,
        capture_steps=False,
        start=Coord(x=0, y=0),
        goal=Coord(x=width - 1, y=height - 1),
    )
    return request, cell_size


def _window_size(request: MazeRequest, cell_size: int) -> tuple[int, int]:
    """Compute the window size for a request without touching pygame.

    Orthogonal: width = W*cell, height = H*cell + HUD.
    Sigma: hex bounding box from the iOS reference layout, plus HUD.
    Delta: triangle bounding box (cell_size*(cols+1)/2 × tri_height*rows), plus HUD.
    """
    if request.maze_type == MazeType.ORTHOGONAL:
        return (request.width * cell_size, request.height * cell_size + HUD_HEIGHT)
    if request.maze_type == MazeType.SIGMA:
        hex_height = math.sqrt(3) * cell_size
        w = int(round(cell_size * (1.5 * request.width + 0.5)))
        h = int(round(hex_height * (request.height + 0.5))) + HUD_HEIGHT
        return (w, h)
    if request.maze_type == MazeType.DELTA:
        tri_height = math.sqrt(3) / 2 * cell_size
        w = int(round(cell_size * (request.width + 1) / 2))
        h = int(round(tri_height * request.height)) + HUD_HEIGHT
        return (w, h)
    raise NotImplementedError(f"window sizing for {request.maze_type.value}")


def _is_solved(cells) -> bool:
    return any(c.is_active and c.is_goal for c in cells)


def _draw_hud(
    surface: pygame.Surface,
    font: pygame.font.Font,
    request: MazeRequest,
    show_heatmap: bool,
    show_solution: bool,
    solved: bool,
) -> None:
    pygame.draw.rect(surface, HUD_BG, pygame.Rect(0, 0, surface.get_width(), HUD_HEIGHT))
    title = f"{request.maze_type.value} · {request.algorithm.value}  {request.width}×{request.height}"
    move_hint = _HUD_HINT_BY_TYPE.get(request.maze_type, "")
    hints = (
        f"H heatmap:{'on' if show_heatmap else 'off'}    "
        f"S solution:{'on' if show_solution else 'off'}    "
        f"R regen    M settings    {move_hint}"
    )
    surface.blit(font.render(title, True, HUD_TITLE_COLOR), (12, 8))
    surface.blit(font.render(hints, True, HUD_HINT_COLOR), (12, 30))
    if solved:
        msg = font.render("Solved!", True, (16, 130, 60))
        surface.blit(msg, msg.get_rect(midright=(surface.get_width() - 12, HUD_HEIGHT // 2)))


def _draw_solved_overlay(
    surface: pygame.Surface,
    rect: pygame.Rect,
    big_font: pygame.font.Font,
    hint_font: pygame.font.Font,
) -> None:
    overlay = pygame.Surface(rect.size, pygame.SRCALPHA)
    overlay.fill(SOLVED_OVERLAY_RGBA)
    surface.blit(overlay, rect.topleft)
    text = big_font.render("Solved!", True, SOLVED_TEXT_COLOR)
    text_rect = text.get_rect(center=rect.center)
    surface.blit(text, text_rect)
    hint = hint_font.render("Press R for a new maze", True, SOLVED_TEXT_COLOR)
    surface.blit(hint, hint.get_rect(midtop=(rect.centerx, text_rect.bottom + 8)))


def _apply_new_request(
    new_request: MazeRequest,
    old_maze: Maze,
    screen: pygame.Surface,
) -> tuple[Maze, object, int, pygame.Surface]:
    """Create a new Maze + Renderer for *new_request*.

    Resizes the display window when the new dimensions differ from the
    current window.  Returns ``(maze, renderer, cell_size, screen)``; the
    returned *screen* may be a new surface if the window was resized.

    Raises ``MazeGenerationError`` on incompatible type/algorithm combos so
    the caller can surface the error back to the menu without crashing.
    """
    cell_size, _, _ = _DEFAULTS.get(new_request.maze_type, (28, 0, 0))
    new_size = _window_size(new_request, cell_size)
    if new_size != screen.get_size():
        screen = pygame.display.set_mode(new_size)
    new_maze = Maze(new_request)  # raises MazeGenerationError if incompatible
    old_maze.close()
    renderer = make_renderer(new_request.maze_type, screen, cell_size, offset=(0, HUD_HEIGHT))
    return new_maze, renderer, cell_size, screen


def main(argv: list[str] | None = None) -> None:
    args = _parse_args(argv)
    request, cell_size = _build_request(args)
    key_map = _KEYS_BY_TYPE[request.maze_type]

    pygame.init()
    pygame.key.set_repeat(_GAMEPLAY_REPEAT_DELAY, _GAMEPLAY_REPEAT_INTERVAL)
    pygame.display.set_caption(
        f"Mazer — {request.maze_type.value} · {request.algorithm.value} {request.width}×{request.height}"
    )

    screen = pygame.display.set_mode(_window_size(request, cell_size))
    clock = pygame.time.Clock()
    hud_font = pygame.font.SysFont(None, 22)
    big_font = pygame.font.SysFont(None, 72)

    maze = Maze(request)
    renderer = make_renderer(request.maze_type, screen, cell_size, offset=(0, HUD_HEIGHT))
    gradient = generate_gradient()
    renderer.set_gradient(gradient)
    show_heatmap = False
    show_solution = False
    # Once a chord fires from a multi-arrow KEYDOWN, mark every held arrow
    # as consumed so the *other* arrow's eventual KEYDOWN doesn't fire a
    # second move. Cleared on the matching KEYUP.
    arrows_consumed: set[int] = set()
    drag = _DragState()
    # Track which keys are physically held so we can distinguish a fresh
    # KEYDOWN from a repeat KEYDOWN generated by pygame.key.set_repeat.
    # Non-movement keys (H/S/R/M) only respond to fresh presses.
    keys_held: set[int] = set()

    menu_state: MenuState | None = None
    menu_layout: MenuLayout | None = None
    # Window size saved just before the menu opens; restored if the user
    # cancels.  None when the menu is not open (or when the window was
    # already large enough and no resize was needed).
    pre_menu_size: tuple[int, int] | None = None

    def _commit_menu_result(open_: bool, new_request) -> None:
        """Apply a menu result to the running game state.

        Mutates the enclosing ``main`` scope via ``nonlocal``.
        """
        nonlocal maze, renderer, cell_size, screen, request, key_map, gradient
        nonlocal menu_state, menu_layout, pre_menu_size
        if not open_:
            if new_request is not None:
                try:
                    maze, renderer, cell_size, screen = _apply_new_request(
                        new_request, maze, screen
                    )
                    request = new_request
                    key_map = _KEYS_BY_TYPE.get(request.maze_type, ORTHOGONAL_KEYS)
                    gradient = generate_gradient()
                    renderer.set_gradient(gradient)
                    arrows_consumed.clear()
                    drag.end()
                    pygame.display.set_caption(
                        f"Mazer — {request.maze_type.value} · "
                        f"{request.algorithm.value} {request.width}×{request.height}"
                    )
                except MazeGenerationError:
                    menu_state.set_generation_error()
                    open_ = True
            if not open_:
                # Menu is truly closing.  If we expanded the window to fit
                # the menu panel and the user cancelled (no new maze was
                # applied), shrink back to the original game window size.
                if new_request is None and pre_menu_size is not None:
                    if screen.get_size() != pre_menu_size:
                        screen = pygame.display.set_mode(pre_menu_size)
                        renderer = make_renderer(
                            request.maze_type, screen, cell_size, offset=(0, HUD_HEIGHT)
                        )
                        renderer.set_gradient(gradient)
                pre_menu_size = None
                keys_held.clear()
                pygame.key.set_repeat(_GAMEPLAY_REPEAT_DELAY, _GAMEPLAY_REPEAT_INTERVAL)
                menu_state = None
                menu_layout = None

    try:
        running = True
        while running:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    running = False

                # ---- Menu open: route all input to the menu ----------------
                elif menu_state is not None:
                    if event.type == pygame.KEYDOWN:
                        open_, new_request = menu_state.handle_keydown(event.key)
                        _commit_menu_result(open_, new_request)
                    elif event.type == pygame.KEYUP:
                        open_, new_request = menu_state.handle_keyup(event.key)
                        _commit_menu_result(open_, new_request)
                    elif event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
                        if menu_layout is not None:
                            open_, new_request = menu_state.handle_mousedown(event.pos, menu_layout)
                            _commit_menu_result(open_, new_request)
                    elif event.type == pygame.MOUSEBUTTONUP and event.button == 1:
                        if menu_layout is not None:
                            open_, new_request = menu_state.handle_mouseup(event.pos, menu_layout)
                            _commit_menu_result(open_, new_request)

                # ---- Normal gameplay ----------------------------------------
                elif event.type == pygame.KEYDOWN:
                    is_repeat = event.key in keys_held
                    keys_held.add(event.key)
                    if event.key == pygame.K_ESCAPE:
                        if not is_repeat:
                            running = False
                    elif event.key == pygame.K_m:
                        if not is_repeat:
                            menu_state = MenuState(request)
                            menu_layout = None
                            keys_held.clear()
                            pygame.key.set_repeat(300, 60)
                            # Enlarge the window if it's too small to show the
                            # full menu panel, and remember the original size so
                            # we can restore it if the user cancels.
                            pre_menu_size = screen.get_size()
                            need_w = max(screen.get_width(), _MENU_MIN_WINDOW_W)
                            need_h = max(screen.get_height(), _MENU_MIN_WINDOW_H)
                            if (need_w, need_h) != pre_menu_size:
                                screen = pygame.display.set_mode((need_w, need_h))
                            else:
                                pre_menu_size = None  # no resize — nothing to restore
                    elif event.key == pygame.K_h:
                        if not is_repeat:
                            show_heatmap = not show_heatmap
                    elif event.key == pygame.K_s:
                        if not is_repeat:
                            show_solution = not show_solution
                    elif event.key in (pygame.K_r, pygame.K_n):
                        if not is_repeat:
                            maze.close()
                            maze = Maze(request)
                            gradient = generate_gradient(gradient.base)
                            renderer.set_gradient(gradient)
                            arrows_consumed.clear()
                            drag.end()
                    elif event.key in ARROW_KEYS:
                        if event.key in arrows_consumed:
                            continue
                        keys = pygame.key.get_pressed()
                        direction = _resolve_chord(
                            keys[pygame.K_UP],
                            keys[pygame.K_DOWN],
                            keys[pygame.K_LEFT],
                            keys[pygame.K_RIGHT],
                        )
                        if direction is not None:
                            maze.move(direction)
                            held_arrows = [k for k in ARROW_KEYS if keys[k]]
                            if len(held_arrows) > 1:
                                arrows_consumed.update(held_arrows)
                    elif event.key in key_map:
                        maze.move(key_map[event.key])
                elif event.type == pygame.KEYUP:
                    keys_held.discard(event.key)
                    if event.key in ARROW_KEYS:
                        arrows_consumed.discard(event.key)
                elif event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
                    if solved:
                        maze.close()
                        maze = Maze(request)
                        gradient = generate_gradient(gradient.base)
                        renderer.set_gradient(gradient)
                        arrows_consumed.clear()
                        drag.end()
                    else:
                        drag.begin(event.pos)
                elif event.type == pygame.MOUSEMOTION:
                    drag.motion(event.pos, maze, cell_size, request.maze_type)
                elif event.type == pygame.MOUSEBUTTONUP and event.button == 1:
                    drag.end()

            cells = maze.cells()
            solved = _is_solved(cells)

            screen.fill((20, 20, 24))
            renderer.draw(cells, show_heatmap=show_heatmap, show_solution=show_solution)
            if solved:
                _draw_solved_overlay(screen, renderer.maze_rect(cells), big_font, hud_font)
            _draw_hud(screen, hud_font, request, show_heatmap, show_solution, solved)
            if menu_state is not None:
                menu_layout = draw_menu(screen, menu_state, hud_font)

            pygame.display.flip()
            clock.tick(60)
    finally:
        maze.close()
        pygame.quit()


if __name__ == "__main__":
    main()
