"""Pygame entry point: window, default maze, and game loop.

Defaults are picked per maze type. Orthogonal: 20×20 grid, ~28px cells —
the same band the iOS reference app's "medium" preset uses. Sigma: 11×10
grid at 26px so the hex bounding box lands in a similar window footprint
without becoming uncomfortably tall (sqrt(3) ≈ 1.73 makes hex windows
naturally taller than square ones).

CLI:
    python -m mazer                     # default Orthogonal
    python -m mazer --type sigma        # hexagonal grid
    python -m mazer --type delta        # triangular grid
    python -m mazer --type rhombic      # 45°-rotated diamond grid
    python -m mazer --type upsilon      # octagon + square grid
    python -m mazer --type sigma --width 13 --height 11 --algo HuntAndKill
    python -m mazer --animate           # animate first maze generation

Movement input (works for every maze type):
    Single arrow keys → cardinal direction (UP/DOWN/LEFT/RIGHT).
    Held arrow chords → diagonal direction:
        ↑ + →  → UPPER_RIGHT
        ↑ + ←  → UPPER_LEFT
        ↓ + →  → LOWER_RIGHT
        ↓ + ←  → LOWER_LEFT
    Left mouse button on an *adjacent linked* cell → move there (single
    tap). Click-and-drag across the grid → chains moves cell-by-cell as
    the cursor crosses open walls (continuous trackpad/mouse navigation).

    The Rust ``make_move`` has built-in fallback for every direction
    (e.g. UPPER_RIGHT tries UpperRight → Up → Right), so chords work
    naturally on orthogonal too — pressing ↑+→ moves up if available,
    else right. Same forgiving feel as the iOS app's eight-way controls.

Sigma/Delta also keep the legacy "hex roguelike" key layout for muscle memory:
    W                UP             Q                UPPER_LEFT
    X                DOWN           E                UPPER_RIGHT
                                    Z                LOWER_LEFT
                                    C                LOWER_RIGHT

Rhombic uses the four diagonal keys only (no UP/DOWN cardinals):
    Q                UPPER_LEFT     E                UPPER_RIGHT
    Z                LOWER_LEFT     C                LOWER_RIGHT

Upsilon uses the same eight-way layout as Sigma (octagons connect in all
eight directions; squares use the cardinal subset, resolved by the Rust):
    W                UP             Q                UPPER_LEFT
    X                DOWN           E                UPPER_RIGHT
                                    Z                LOWER_LEFT
                                    C                LOWER_RIGHT

Common keys:
    H                Toggle heatmap overlay
    S                Toggle solution-path overlay
    G                Toggle animate-generation mode (next R/N plays step-by-step)
    R / N            Regenerate (animates if G mode is on)
    M                Open settings menu (change type, algorithm, size)
    Esc              Quit (cancel animation if animating; close menu if menu is open).

Open-exit dots: the active cell shows small white dots near each open
edge — affordance equivalent to the iOS D-pad's per-direction enabled
state. If a key seems "not to move you", check the dots.
"""

from __future__ import annotations

import argparse
import dataclasses
import math
import sys
from collections import deque

import pygame

from mazer.maze import Cell, Maze, MazeGenerationError
from mazer.types import Algorithm, Coord, Direction, MazeRequest, MazeType
from mazer.ui.menu import MenuLayout, MenuState, draw_menu
from mazer.ui.renderer import (
    OFF_WHITE,
    generate_gradient,
    make_renderer,
)


HUD_HEIGHT = 56

# Minimum window size that ensures the settings menu panel (460 px wide,
# ~338 px tall + HUD) is fully visible.  Windows narrower or shorter than
# this are temporarily enlarged when the menu opens and restored on close.
_MENU_MIN_WINDOW_W = 500
_MENU_MIN_WINDOW_H = 450

# Per-side grid cap when animation mode is active.  16×16 = 256 cells keeps
# even Aldous-Broder step counts manageable (O(n log n) expected steps).
ANIM_MAX_W: int = 30   # max width (cols) allowed when animation mode is on
ANIM_MAX_H: int = 20   # max height (rows) allowed when animation mode is on

# Fraction of the primary display dimensions used as the safe available area
# for maze windows (leaves room for OS taskbars, the macOS dock, etc.).
SCREEN_MARGIN_W: float = 0.95
SCREEN_MARGIN_H: float = 0.90

# Key-repeat settings for gameplay movement.  A KEYDOWN event for a key
# that is already held is a repeat (generated by pygame's set_repeat).
# Non-movement actions (H/S/R/M) are filtered to first-press only.
_GAMEPLAY_REPEAT_DELAY = 200     # ms before first auto-move when key held
_GAMEPLAY_REPEAT_INTERVAL = 100  # ms between subsequent auto-moves

# Hold-to-scroll on menu arrow buttons (mirrors pygame.key.set_repeat values
# used when the menu is open so mouse and keyboard feel identical).
_MENU_ARROW_REPEAT_DELAY = 300    # ms held before first auto-repeat fires
_MENU_ARROW_REPEAT_INTERVAL = 60  # ms between subsequent repeats

# Per-maze-type defaults. Tuple of (cell_size, width, height) — the
# default algorithm is RecursiveBacktracker for all types because it
# produces winding paths that show off the heatmap and solution-path
# overlays well; user can override with --algo.
# All defaults target a landscape aspect ratio of at least 1.75:1
# (width ≥ 1.75 × height) so the window opens wider than it is tall.
# Rhombic: 14×8 — goal=(13,7), (13+7)=20 satisfies (x+y)%2==0 (only
# even-sum cells exist); cell_size=36 gives a diagonal≈51px for clicking.
_DEFAULTS: dict[MazeType, tuple[int, int, int]] = {
    MazeType.ORTHOGONAL: (28, 28, 16),   # 1.75:1
    MazeType.SIGMA: (26, 14, 8),         # 1.75:1
    MazeType.DELTA: (30, 21, 12),        # 1.75:1
    MazeType.RHOMBIC: (36, 14, 8),       # 1.75:1
    # Upsilon: cell_size=40 gives step≈28px; 18×10 produces a ~521×351 maze.
    MazeType.UPSILON: (40, 18, 10),      # 1.80:1
}

ORTHOGONAL_KEYS: dict[int, Direction] = {
    pygame.K_UP: Direction.UP,
    pygame.K_DOWN: Direction.DOWN,
    pygame.K_LEFT: Direction.LEFT,
    pygame.K_RIGHT: Direction.RIGHT,
}

# Sigma uses the standard hex roguelike layout: W/Q/E across the top row
# of letters and Z/X/C across the bottom row, with the grid pivot point
# (S/D in QWERTY) deliberately *unbound* so a typo in either row never
# silently wraps. ↑ and ↓ also map to UP/DOWN as a common-sense affordance.
SIGMA_KEYS: dict[int, Direction] = {
    pygame.K_UP: Direction.UP,
    pygame.K_w: Direction.UP,
    pygame.K_DOWN: Direction.DOWN,
    pygame.K_x: Direction.DOWN,
    pygame.K_q: Direction.UPPER_LEFT,
    pygame.K_e: Direction.UPPER_RIGHT,
    pygame.K_z: Direction.LOWER_LEFT,
    pygame.K_c: Direction.LOWER_RIGHT,
}

# Delta uses the same six-direction layout as Sigma. The Rust make_move
# fallback resolves each direction to the correct triangle edge for the
# current cell orientation (Normal vs Inverted).
DELTA_KEYS: dict[int, Direction] = SIGMA_KEYS

# Valid move directions for Rhombic — all diagonal.
_RHOMBIC_VALID_DIRECTIONS = frozenset({
    Direction.UPPER_RIGHT, Direction.LOWER_RIGHT,
    Direction.LOWER_LEFT, Direction.UPPER_LEFT,
})

# Single-arrow cardinal → nearest Rhombic diagonal, consistent with the
# 90°-sector drag mapping: ↑=270°→UpperRight, →=0°→LowerRight,
# ↓=90°→LowerLeft, ←=180°→UpperLeft.
_RHOMBIC_CARDINAL_TO_DIAGONAL: dict[Direction, Direction] = {
    Direction.UP:    Direction.UPPER_RIGHT,
    Direction.RIGHT: Direction.LOWER_RIGHT,
    Direction.DOWN:  Direction.LOWER_LEFT,
    Direction.LEFT:  Direction.UPPER_LEFT,
}

# Rhombic has only four diagonal directions. No W/X (UP/DOWN cardinals)
# because Rhombic cells don't connect cardinally; Q/E/Z/C cover all moves.
# Arrow chords (↑+→ etc.) still work and produce the four diagonals.
RHOMBIC_KEYS: dict[int, Direction] = {
    pygame.K_q: Direction.UPPER_LEFT,
    pygame.K_e: Direction.UPPER_RIGHT,
    pygame.K_z: Direction.LOWER_LEFT,
    pygame.K_c: Direction.LOWER_RIGHT,
}

# Upsilon has octagons (8 directions) and squares (4 cardinal directions).
# Use the full eight-way layout; the Rust make_move handles the square cells'
# diagonal inputs by falling back to the cardinal component (Up → Up, etc.).
UPSILON_KEYS: dict[int, Direction] = SIGMA_KEYS

_KEYS_BY_TYPE: dict[MazeType, dict[int, Direction]] = {
    MazeType.ORTHOGONAL: ORTHOGONAL_KEYS,
    MazeType.SIGMA: SIGMA_KEYS,
    MazeType.DELTA: DELTA_KEYS,
    MazeType.RHOMBIC: RHOMBIC_KEYS,
    MazeType.UPSILON: UPSILON_KEYS,
}

ARROW_KEYS: tuple[int, ...] = (pygame.K_UP, pygame.K_DOWN, pygame.K_LEFT, pygame.K_RIGHT)

_HUD_HINT_BY_TYPE: dict[MazeType, str] = {
    MazeType.ORTHOGONAL: "arrows + chords + drag/click",
    MazeType.SIGMA: "chords / W·Q·E·Z·X·C / drag/click",
    MazeType.DELTA: "chords / W·Q·E·Z·X·C / drag/click",
    MazeType.RHOMBIC: "Q·E·Z·C diagonals + chords + drag/click",
    MazeType.UPSILON: "chords / W·Q·E·Z·X·C / drag/click",
}


# Adjacent directions (±45° on the 8-direction wheel) to try when the
# primary direction is walled off (orthogonal and sigma).  Delta uses a
# separate orientation-aware vertical slide — see _move_with_slide.
_SLIDE_ALTS: dict[Direction, tuple[Direction, Direction]] = {
    Direction.UP:          (Direction.UPPER_LEFT,  Direction.UPPER_RIGHT),
    Direction.UPPER_RIGHT: (Direction.UP,          Direction.RIGHT),
    Direction.RIGHT:       (Direction.UPPER_RIGHT, Direction.LOWER_RIGHT),
    Direction.LOWER_RIGHT: (Direction.RIGHT,       Direction.DOWN),
    Direction.DOWN:        (Direction.LOWER_RIGHT, Direction.LOWER_LEFT),
    Direction.LOWER_LEFT:  (Direction.DOWN,        Direction.LEFT),
    Direction.LEFT:        (Direction.LOWER_LEFT,  Direction.UPPER_LEFT),
    Direction.UPPER_LEFT:  (Direction.LEFT,        Direction.UP),
}

# Directions that represent horizontal movement in a delta maze (produced
# by _delta_horizontal converting a LEFT/RIGHT arrow to the orientation-
# correct diagonal).
_DELTA_HORIZONTAL_DIRS = frozenset({
    Direction.UPPER_LEFT, Direction.UPPER_RIGHT,
    Direction.LOWER_LEFT, Direction.LOWER_RIGHT,
})


def _move_with_slide(maze, direction: Direction, maze_type: MazeType) -> bool:
    """Fire *direction*; if blocked, try a slide alternative.

    Rhombic: no slide alts — only four diagonal directions exist and the
    Rust's built-in fallback already handles any secondary attempt.  Sending
    a cardinal slide alt (e.g. RIGHT as alt for UPPER_RIGHT) would cause the
    Rust to fall back to LOWER_RIGHT, which is a valid Rhombic direction but
    in the opposite vertical, producing unexpected moves.

    Delta horizontal slide is orientation-aware: when UPPER/LOWER_RIGHT/LEFT
    is blocked, slide to the one vertical neighbor that genuinely exists for
    the active cell's orientation — Normal cells connect downward only,
    Inverted cells connect upward only.  Using the wrong vertical would hit
    the Rust's diagonal fallback and land on the *opposite* horizontal
    neighbour (the cell just left), causing back-and-forth oscillation.

    All other maze types use the ±45° direction-wheel table (_SLIDE_ALTS).
    """
    if maze.move(direction):
        return True
    if maze_type == MazeType.RHOMBIC:
        return False
    if maze_type == MazeType.DELTA and direction in _DELTA_HORIZONTAL_DIRS:
        cells = maze.cells()
        active = next((c for c in cells if c.is_active), None)
        if active is not None:
            vertical = (
                Direction.DOWN if active.orientation.lower() == "normal"
                else Direction.UP
            )
            return maze.move(vertical)
        return False
    for alt in _SLIDE_ALTS.get(direction, ()):
        if maze.move(alt):
            return True
    return False


def _delta_horizontal(direction: Direction, cells: list) -> Direction:
    """Map LEFT/RIGHT to the orientation-correct diagonal for the active delta cell.

    Normal cells (apex up) have UpperLeft/UpperRight as horizontal neighbors.
    Inverted cells (apex down) have LowerLeft/LowerRight.  Sending the exact
    diagonal skips the Rust fallback's intermediate attempt at the wrong
    diagonal (which has no neighbor on the current cell), preventing the
    one-cell-then-stuck behaviour when holding LEFT or RIGHT in a delta maze.
    """
    active = next((c for c in cells if c.is_active), None)
    if active is None:
        return direction
    is_normal = active.orientation.lower() == "normal"
    if direction == Direction.LEFT:
        return Direction.UPPER_LEFT if is_normal else Direction.LOWER_LEFT
    if direction == Direction.RIGHT:
        return Direction.UPPER_RIGHT if is_normal else Direction.LOWER_RIGHT
    return direction


def _resolve_chord(up: bool, down: bool, left: bool, right: bool) -> Direction | None:
    """Resolve held arrow keys to a single Direction.

    Diagonal combinations win over cardinals. Opposing pairs (UP+DOWN,
    LEFT+RIGHT) cancel out — they're treated as if the perpendicular axis
    isn't held, so e.g. UP+DOWN+RIGHT resolves to RIGHT.

    Returns ``None`` if no arrow is held (callers shouldn't reach this
    case on KEYDOWN — defensive only).
    """
    vertical = up ^ down  # cancel if both
    horizontal = left ^ right
    if vertical and horizontal:
        if up and right:
            return Direction.UPPER_RIGHT
        if up and left:
            return Direction.UPPER_LEFT
        if down and right:
            return Direction.LOWER_RIGHT
        if down and left:
            return Direction.LOWER_LEFT
    if vertical:
        return Direction.UP if up else Direction.DOWN
    if horizontal:
        return Direction.LEFT if left else Direction.RIGHT
    return None


# Orthogonal: eight 45° sectors.  Angle 0° = rightward (+x), clockwise
# (y-down screen coords).  Each sector boundary is at multiples of 45°
# offset by 22.5° so the cardinal and diagonal centres are equidistant.
# Diagonals are passed straight to the Rust ``make_move`` which tries the
# vertical component first, then the horizontal — e.g. UPPER_RIGHT tries
# Up → Right — giving the liberal fallback the user feels on the trackpad.
_ORTHO_SECTOR_DIRECTIONS = (
    Direction.RIGHT,        # sector 0: 337.5°–22.5°
    Direction.LOWER_RIGHT,  # sector 1: 22.5°–67.5°
    Direction.DOWN,         # sector 2: 67.5°–112.5°
    Direction.LOWER_LEFT,   # sector 3: 112.5°–157.5°
    Direction.LEFT,         # sector 4: 157.5°–202.5°
    Direction.UPPER_LEFT,   # sector 5: 202.5°–247.5°
    Direction.UP,           # sector 6: 247.5°–292.5°
    Direction.UPPER_RIGHT,  # sector 7: 292.5°–337.5°
)

# Sigma: six 60° sectors mapped to hex directions, indexed by
# ``int((angle_degrees + 30) % 360 / 60)``.  Angle 0° = rightward (screen
# x+), increasing clockwise (y-down screen coords).  Centers per sector:
# 330° UPPER_RIGHT, 30° LOWER_RIGHT, 90° DOWN, 150° LOWER_LEFT,
# 210° UPPER_LEFT, 270° UP.
_SIGMA_SECTOR_DIRECTIONS = (
    Direction.UPPER_RIGHT,  # sector 0: 300°–360° / 0°–30°
    Direction.LOWER_RIGHT,  # sector 1: 30°–90°
    Direction.DOWN,         # sector 2: 90°–150°
    Direction.LOWER_LEFT,   # sector 3: 150°–210°
    Direction.UPPER_LEFT,   # sector 4: 210°–270°
    Direction.UP,           # sector 5: 270°–330°
)

# Rhombic: four 90° sectors, boundaries at the cardinal axes.
# Angle 0° = rightward (screen x+), clockwise.  Sector = int(angle / 90) % 4.
#   0°–90°   → LOWER_RIGHT  (center 45°)
#   90°–180° → LOWER_LEFT   (center 135°)
#   180°–270°→ UPPER_LEFT   (center 225°)
#   270°–360°→ UPPER_RIGHT  (center 315°)
_RHOMBIC_SECTOR_DIRECTIONS = (
    Direction.LOWER_RIGHT,  # sector 0: 0°–90°
    Direction.LOWER_LEFT,   # sector 1: 90°–180°
    Direction.UPPER_LEFT,   # sector 2: 180°–270°
    Direction.UPPER_RIGHT,  # sector 3: 270°–360°
)


def _direction_from_vector(dx: float, dy: float, maze_type: MazeType) -> Direction | None:
    """Resolve a drag vector to a Direction based on maze type.

    Orthogonal/Delta: angle mapped to nearest of 8 directions (45° sectors).
      Diagonal directions are passed to the Rust which applies per-type
      fallback — e.g. UPPER_RIGHT on a Normal delta cell tries UpperRight
      directly; on an Inverted cell the Rust resolves it to Up or Right.
    Sigma: angle mapped to nearest of 6 hex directions (60° sectors).
    Rhombic: angle mapped to nearest of 4 diagonal directions (90° sectors).
    Returns None for zero-length vectors or unimplemented maze types.
    """
    if dx == 0 and dy == 0:
        return None
    angle = (math.degrees(math.atan2(dy, dx)) + 360) % 360
    if maze_type in (MazeType.ORTHOGONAL, MazeType.DELTA, MazeType.UPSILON):
        sector = int((angle + 22.5) / 45) % 8
        return _ORTHO_SECTOR_DIRECTIONS[sector]
    if maze_type == MazeType.SIGMA:
        sector = int((angle + 30) % 360 / 60)
        return _SIGMA_SECTOR_DIRECTIONS[sector]
    if maze_type == MazeType.RHOMBIC:
        sector = int(angle / 90) % 4
        return _RHOMBIC_SECTOR_DIRECTIONS[sector]
    return None


class _DragState:
    """Swipe-to-move state machine.

    Click anywhere on the maze and hold.  As the cursor moves, the drag
    vector from the last-fired position is resolved to a direction; when
    it exceeds the threshold (``cell_size * 0.6``) a move fires and the
    anchor resets to the current position so the next move requires
    another threshold-worth of drag.  Works like a joystick — direction
    of travel determines movement, not which cell the cursor is on.
    """

    def __init__(self) -> None:
        self.active = False
        self._origin: tuple[int, int] | None = None

    def begin(self, pos: tuple[int, int]) -> None:
        """Start a drag session, recording the cursor anchor point."""
        self.active = True
        self._origin = pos

    def motion(
        self,
        pos: tuple[int, int],
        maze,
        cell_size: int,
        maze_type: MazeType,
    ) -> bool:
        """Handle MOUSEMOTION. Fires a move when the accumulated drag exceeds the threshold."""
        if not self.active or self._origin is None:
            return False
        ox, oy = self._origin
        dx = pos[0] - ox
        dy = pos[1] - oy
        if math.hypot(dx, dy) < cell_size * 0.6:
            return False
        direction = _direction_from_vector(dx, dy, maze_type)
        if direction is None:
            return False
        fired = maze.move(direction)
        self._origin = pos
        return fired

    def end(self) -> None:
        self.active = False
        self._origin = None


ANIM_STEP_INTERVAL_MS: float = 15.0


class AnimationState:
    """Step-by-step maze generation animation controller.

    Pre-loads all generation steps; ``tick()`` advances by elapsed wall-clock
    time and returns True when the last step is reached.  ``skip()`` jumps to
    the final frame immediately, idempotent if already done.
    """

    def __init__(self, steps: list) -> None:
        self.steps = steps
        self.current_step: int = 0
        self.done: bool = len(steps) == 0
        self._accum_ms: float = 0.0

    def tick(self, elapsed_ms: float) -> bool:
        """Advance by *elapsed_ms*. Returns True when animation completes."""
        if self.done or not self.steps:
            self.done = True
            return False
        self._accum_ms += elapsed_ms
        steps_to_advance = int(self._accum_ms / ANIM_STEP_INTERVAL_MS)
        if steps_to_advance > 0:
            self._accum_ms -= steps_to_advance * ANIM_STEP_INTERVAL_MS
            self.current_step = min(
                self.current_step + steps_to_advance, len(self.steps) - 1
            )
        if self.current_step >= len(self.steps) - 1:
            self.done = True
            return True
        return False

    def skip(self) -> None:
        """Jump to the final step."""
        if self.steps:
            self.current_step = len(self.steps) - 1
        self.done = True


class SolutionAnimState:
    """Reveal solution path one cell at a time, sorted by distance from start."""

    def __init__(self, solution_cells: list) -> None:
        sorted_cells = sorted(solution_cells, key=lambda c: c.distance)
        self.coords: list = [c.coord for c in sorted_cells]
        self.revealed_count: int = 0
        self.done: bool = len(self.coords) == 0
        self._accum_ms: float = 0.0

    @property
    def revealed_set(self) -> frozenset:
        return frozenset(self.coords[: self.revealed_count])

    def tick(self, elapsed_ms: float) -> bool:
        """Advance by elapsed_ms. Returns True when all cells are revealed."""
        if self.done:
            return False
        self._accum_ms += elapsed_ms
        steps = int(self._accum_ms / ANIM_STEP_INTERVAL_MS)
        if steps > 0:
            self._accum_ms -= steps * ANIM_STEP_INTERVAL_MS
            self.revealed_count = min(self.revealed_count + steps, len(self.coords))
        if self.revealed_count >= len(self.coords):
            self.done = True
            return True
        return False


HUD_BG = OFF_WHITE
HUD_TITLE_COLOR = (40, 40, 40)
HUD_HINT_COLOR = (90, 90, 90)
SOLVED_TEXT_COLOR = (255, 255, 255)
SOLVED_OVERLAY_RGBA = (0, 0, 0, 130)


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(prog="python -m mazer", description="Mazer Pygame UI.")
    parser.add_argument(
        "--type",
        dest="maze_type",
        choices=[m.value.lower() for m in (MazeType.ORTHOGONAL, MazeType.SIGMA, MazeType.DELTA, MazeType.RHOMBIC, MazeType.UPSILON)],
        default=MazeType.ORTHOGONAL.value.lower(),
        help="Maze type: orthogonal (default), sigma (hex), delta (triangular), rhombic (diamond), or upsilon (octagon+square).",
    )
    parser.add_argument("--width", type=int, default=None, help="Grid width (cells). Default depends on type.")
    parser.add_argument("--height", type=int, default=None, help="Grid height (cells). Default depends on type.")
    parser.add_argument(
        "--algo",
        default=Algorithm.RECURSIVE_BACKTRACKER.value,
        help=f"Generation algorithm. Default {Algorithm.RECURSIVE_BACKTRACKER.value}.",
    )
    parser.add_argument(
        "--animate",
        action="store_true",
        default=False,
        help="Animate maze generation on first launch.",
    )
    return parser.parse_args(argv)


def _build_request(args: argparse.Namespace) -> tuple[MazeRequest, int]:
    """Translate CLI args into a (request, cell_size) pair."""
    maze_type = MazeType(args.maze_type.capitalize())
    cell_size, default_w, default_h = _DEFAULTS[maze_type]
    width = args.width if args.width is not None else default_w
    height = args.height if args.height is not None else default_h
    algorithm = Algorithm(args.algo)
    goal_x, goal_y = width - 1, height - 1
    if maze_type == MazeType.RHOMBIC and (goal_x + goal_y) % 2 != 0:
        # Only (x+y)%2==0 cells exist; adjust goal by one step.
        goal_x = max(0, goal_x - 1)
    request = MazeRequest(
        maze_type=maze_type,
        width=width,
        height=height,
        algorithm=algorithm,
        capture_steps=False,
        start=Coord(x=0, y=0),
        goal=Coord(x=goal_x, y=goal_y),
    )
    return request, cell_size


def _window_size(request: MazeRequest, cell_size: int) -> tuple[int, int]:
    """Compute the window size for a request without touching pygame.

    Orthogonal: width = W*cell, height = H*cell + HUD.
    Sigma: hex bounding box from the iOS reference layout, plus HUD.
    Delta: triangle bounding box (cell_size*(cols+1)/2 × tri_height*rows), plus HUD.
    Rhombic: diamond bounding box from RhombicMazeView (half_diagonal*max_x + diagonal),
      plus HUD.  max_x = width-1, max_y = height-1.
    """
    if request.maze_type == MazeType.ORTHOGONAL:
        return (request.width * cell_size, request.height * cell_size + HUD_HEIGHT)
    if request.maze_type == MazeType.SIGMA:
        hex_height = math.sqrt(3) * cell_size
        w = int(round(cell_size * (1.5 * request.width + 0.5)))
        h = int(round(hex_height * (request.height + 0.5))) + HUD_HEIGHT
        return (w, h)
    if request.maze_type == MazeType.DELTA:
        tri_height = math.sqrt(3) / 2 * cell_size
        w = int(round(cell_size * (request.width + 1) / 2))
        h = int(round(tri_height * request.height)) + HUD_HEIGHT
        return (w, h)
    if request.maze_type == MazeType.RHOMBIC:
        diagonal = cell_size * math.sqrt(2)
        half_diagonal = diagonal / 2
        w = int(round(half_diagonal * (request.width - 1) + diagonal))
        h = int(round(half_diagonal * (request.height - 1) + diagonal)) + HUD_HEIGHT
        return (w, h)
    if request.maze_type == MazeType.UPSILON:
        step = cell_size * math.sqrt(2) / 2
        w = int(round((request.width - 1) * step + cell_size))
        h = int(round((request.height - 1) * step + cell_size)) + HUD_HEIGHT
        return (w, h)
    raise NotImplementedError(f"window sizing for {request.maze_type.value}")


def _max_grid_for_screen(
    maze_type: MazeType, cell_size: int, avail_w: int, avail_h: int
) -> tuple[int, int]:
    """Return (max_cols, max_rows) whose window fits inside avail_w × avail_h.

    Inverts each branch of ``_window_size`` analytically.  Results are clamped
    to at least 2 so a tiny display never produces an invalid request.
    """
    maze_h = max(1, avail_h - HUD_HEIGHT)
    if maze_type == MazeType.ORTHOGONAL:
        return (
            max(2, avail_w // cell_size),
            max(2, maze_h // cell_size),
        )
    if maze_type == MazeType.SIGMA:
        return (
            max(2, int((avail_w / cell_size - 0.5) / 1.5)),
            max(2, int(maze_h / (math.sqrt(3) * cell_size) - 0.5)),
        )
    if maze_type == MazeType.DELTA:
        return (
            max(2, int(avail_w * 2 / cell_size) - 1),
            max(2, int(maze_h / (math.sqrt(3) / 2 * cell_size))),
        )
    if maze_type == MazeType.RHOMBIC:
        diag = cell_size * math.sqrt(2)
        half = diag / 2
        return (
            max(2, int((avail_w - diag) / half) + 1),
            max(2, int((maze_h - diag) / half) + 1),
        )
    if maze_type == MazeType.UPSILON:
        step = cell_size * math.sqrt(2) / 2
        return (
            max(2, int((avail_w - cell_size) / step) + 1),
            max(2, int((maze_h - cell_size) / step) + 1),
        )
    return (40, 40)  # unreachable guard


def _is_solved(cells) -> bool:
    return any(c.is_active and c.is_goal for c in cells)


def _draw_hud(
    surface: pygame.Surface,
    font: pygame.font.Font,
    request: MazeRequest,
    show_heatmap: bool,
    show_solution: bool,
    solved: bool,
    animate_mode: bool = False,
    anim_info: str | None = None,
    hud_msg: str = "",
) -> None:
    pygame.draw.rect(surface, HUD_BG, pygame.Rect(0, 0, surface.get_width(), HUD_HEIGHT))
    title = f"{request.maze_type.value} · {request.algorithm.value}  {request.width}×{request.height}"
    move_hint = _HUD_HINT_BY_TYPE.get(request.maze_type, "")
    if hud_msg:
        hint_text = hud_msg
        hint_color = (220, 120, 20)  # orange — transient warning
    elif anim_info is not None:
        hint_text = anim_info
        hint_color = HUD_HINT_COLOR
    else:
        hint_text = (
            f"H heatmap:{'on' if show_heatmap else 'off'}    "
            f"S solution:{'on' if show_solution else 'off'}    "
            f"R regen    G anim:{'on' if animate_mode else 'off'}    M settings    {move_hint}"
        )
        hint_color = HUD_HINT_COLOR
    surface.blit(font.render(title, True, HUD_TITLE_COLOR), (12, 8))
    surface.blit(font.render(hint_text, True, hint_color), (12, 30))
    if solved:
        msg = font.render("Solved!", True, (16, 130, 60))
        surface.blit(msg, msg.get_rect(midright=(surface.get_width() - 12, HUD_HEIGHT // 2)))


def _draw_solved_overlay(
    surface: pygame.Surface,
    rect: pygame.Rect,
    big_font: pygame.font.Font,
    hint_font: pygame.font.Font,
) -> None:
    overlay = pygame.Surface(rect.size, pygame.SRCALPHA)
    overlay.fill(SOLVED_OVERLAY_RGBA)
    surface.blit(overlay, rect.topleft)
    text = big_font.render("Solved!", True, SOLVED_TEXT_COLOR)
    text_rect = text.get_rect(center=rect.center)
    surface.blit(text, text_rect)
    hint = hint_font.render("Press R / Space / Enter for a new maze", True, SOLVED_TEXT_COLOR)
    surface.blit(hint, hint.get_rect(midtop=(rect.centerx, text_rect.bottom + 8)))


def _apply_new_request(
    new_request: MazeRequest,
    old_maze: Maze,
    screen: pygame.Surface,
) -> tuple[Maze, object, int, pygame.Surface]:
    """Create a new Maze + Renderer for *new_request*.

    Resizes the display window when the new dimensions differ from the
    current window.  Returns ``(maze, renderer, cell_size, screen)``; the
    returned *screen* may be a new surface if the window was resized.

    Raises ``MazeGenerationError`` on incompatible type/algorithm combos so
    the caller can surface the error back to the menu without crashing.
    """
    cell_size, _, _ = _DEFAULTS.get(new_request.maze_type, (28, 0, 0))
    new_size = _window_size(new_request, cell_size)
    if new_size != screen.get_size():
        screen = pygame.display.set_mode(new_size)
    new_maze = Maze(new_request)  # raises MazeGenerationError if incompatible
    old_maze.close()
    renderer = make_renderer(new_request.maze_type, screen, cell_size, offset=(0, HUD_HEIGHT))
    return new_maze, renderer, cell_size, screen


def main(argv: list[str] | None = None) -> None:
    args = _parse_args(argv)
    request, cell_size = _build_request(args)
    key_map = _KEYS_BY_TYPE[request.maze_type]

    pygame.init()
    pygame.key.set_repeat(_GAMEPLAY_REPEAT_DELAY, _GAMEPLAY_REPEAT_INTERVAL)

    # Detect primary display dimensions before the first set_mode call so we
    # can cap grid sizes to what actually fits on screen.
    try:
        _desktop = pygame.display.get_desktop_sizes()
        _sw, _sh = _desktop[0] if _desktop else (1280, 800)
    except Exception:
        _info = pygame.display.Info()
        _sw, _sh = (_info.current_w or 1280), (_info.current_h or 800)
    _avail_w = int(_sw * SCREEN_MARGIN_W)
    _avail_h = int(_sh * SCREEN_MARGIN_H)
    screen_max_sizes: dict[MazeType, tuple[int, int]] = {
        mt: _max_grid_for_screen(mt, _DEFAULTS[mt][0], _avail_w, _avail_h)
        for mt in MazeType
    }

    # Clamp the initial request if CLI args exceed the screen-safe dimensions.
    _smx, _smy = screen_max_sizes[request.maze_type]
    if request.width > _smx or request.height > _smy:
        _cw, _ch = min(request.width, _smx), min(request.height, _smy)
        print(
            f"Warning: {request.width}×{request.height} exceeds screen limit for "
            f"{request.maze_type.value}; clamped to {_cw}×{_ch}",
            file=sys.stderr,
        )
        _goal_x = min(_cw - 1, request.goal.x)
        _goal_y = min(_ch - 1, request.goal.y)
        if request.maze_type == MazeType.RHOMBIC and (_goal_x + _goal_y) % 2 != 0:
            _goal_x = max(0, _goal_x - 1)
        request = dataclasses.replace(
            request, width=_cw, height=_ch, goal=Coord(x=_goal_x, y=_goal_y)
        )

    pygame.display.set_caption(
        f"Mazer — {request.maze_type.value} · {request.algorithm.value} {request.width}×{request.height}"
    )

    screen = pygame.display.set_mode(_window_size(request, cell_size))
    clock = pygame.time.Clock()
    hud_font = pygame.font.SysFont(None, 22)
    big_font = pygame.font.SysFont(None, 72)

    maze = Maze(request)
    renderer = make_renderer(request.maze_type, screen, cell_size, offset=(0, HUD_HEIGHT))
    gradient = generate_gradient()
    renderer.set_gradient(gradient)
    show_heatmap = False
    show_solution = False
    # Once a chord fires from a multi-arrow KEYDOWN, mark every held arrow
    # as consumed so the *other* arrow's eventual KEYDOWN doesn't fire a
    # second move. Cleared on the matching KEYUP.
    arrows_consumed: set[int] = set()
    drag = _DragState()
    # Track which keys are physically held so we can distinguish a fresh
    # KEYDOWN from a repeat KEYDOWN generated by pygame.key.set_repeat.
    # Non-movement keys (H/S/R/M) only respond to fresh presses.
    keys_held: set[int] = set()
    # When the player is on the Solved! screen and holds Space/Enter, the
    # whole screen turns grayscale until release, then a new maze generates.
    solved_btn_pressed: bool = False
    solved: bool = False  # pre-initialised so the event loop can read it on frame 0
    trail: deque = deque(maxlen=3)   # coords of the last 3 vacated cells, index 0 = most recent
    _prev_active_coord = None        # active coord from the previous frame
    _visited_set: set = set()        # all coords the player has ever stood on this maze

    # Sticky animation mode — toggled by G key.  When True, R/N and first
    # launch with --animate generate with capture_steps=True and play the
    # step-by-step animation before handing off to interactive play.
    animate_mode: bool = args.animate
    anim: AnimationState | None = None
    anim_maze: Maze | None = None  # new maze being animated (kept separate for cancel)
    solution_anim: SolutionAnimState | None = None

    menu_state: MenuState | None = None
    menu_layout: MenuLayout | None = None
    # Window size saved just before the menu opens; restored if the user
    # cancels.  None when the menu is not open (or when the window was
    # already large enough and no resize was needed).
    pre_menu_size: tuple[int, int] | None = None
    # Hold-to-scroll state for menu arrow buttons.  Records which arrow
    # (section + delta) is held and when the hold started / last fired.
    _arrow_held: tuple[int, int] | None = None   # (section, delta: -1 or +1)
    _arrow_held_since: int = 0                   # ticks of initial press
    _arrow_last_fire: int = 0                    # ticks of most recent repeat

    # Transient HUD message shown for a fixed duration (e.g. animation-skipped warning).
    _hud_msg: str = ""
    _hud_msg_until: int = 0  # pygame.time.get_ticks() expiry

    def _set_hud_msg(msg: str, duration_ms: int = 4000) -> None:
        nonlocal _hud_msg, _hud_msg_until
        _hud_msg = msg
        _hud_msg_until = pygame.time.get_ticks() + duration_ms

    def _commit_menu_result(open_: bool, new_request) -> None:
        """Apply a menu result to the running game state.

        Mutates the enclosing ``main`` scope via ``nonlocal``.
        """
        nonlocal maze, renderer, cell_size, screen, request, key_map, gradient
        nonlocal menu_state, menu_layout, pre_menu_size, trail, _prev_active_coord
        if not open_:
            if new_request is not None:
                try:
                    maze, renderer, cell_size, screen = _apply_new_request(
                        new_request, maze, screen
                    )
                    request = new_request
                    key_map = _KEYS_BY_TYPE.get(request.maze_type, ORTHOGONAL_KEYS)
                    gradient = generate_gradient()
                    renderer.set_gradient(gradient)
                    trail.clear()
                    _prev_active_coord = None
                    _visited_set.clear()
                    arrows_consumed.clear()
                    drag.end()
                    pygame.display.set_caption(
                        f"Mazer — {request.maze_type.value} · "
                        f"{request.algorithm.value} {request.width}×{request.height}"
                    )
                    if animate_mode:
                        _begin_animation()
                except MazeGenerationError:
                    menu_state.set_generation_error()
                    open_ = True
            if not open_:
                # Menu is truly closing.  If we expanded the window to fit
                # the menu panel and the user cancelled (no new maze was
                # applied), shrink back to the original game window size.
                if new_request is None and pre_menu_size is not None:
                    if screen.get_size() != pre_menu_size:
                        screen = pygame.display.set_mode(pre_menu_size)
                        renderer = make_renderer(
                            request.maze_type, screen, cell_size, offset=(0, HUD_HEIGHT)
                        )
                        renderer.set_gradient(gradient)
                pre_menu_size = None
                keys_held.clear()
                pygame.key.set_repeat(_GAMEPLAY_REPEAT_DELAY, _GAMEPLAY_REPEAT_INTERVAL)
                menu_state = None
                menu_layout = None

    def _begin_animation() -> None:
        """Start step-by-step animation for the current request.

        Returns immediately (no animation) if the grid exceeds ANIM_MAX_W ×
        ANIM_MAX_H — the menu already prevents this for in-game sessions; this
        guard catches the CLI ``--animate`` path on an oversized grid.
        """
        nonlocal anim, anim_maze, solved_btn_pressed, show_solution, solution_anim
        if request.width > ANIM_MAX_W or request.height > ANIM_MAX_H:
            _set_hud_msg(
                f"⚠ Too large to animate ({request.width}×{request.height}"
                f" > {ANIM_MAX_W}×{ANIM_MAX_H})"
                f" — reduce size (M) or disable anim (G)"
            )
            return
        if anim_maze is not None:
            anim_maze.close()
        anim_request = dataclasses.replace(request, capture_steps=True)
        anim_maze = Maze(anim_request)
        all_steps = list(anim_maze.generation_steps())
        anim = AnimationState(all_steps)
        show_solution = False
        solution_anim = None
        renderer.set_gradient(None)
        drag.end()
        arrows_consumed.clear()
        solved_btn_pressed = False

    def _complete_animation() -> None:
        """Finish animation (normal end or skip) — switch to interactive play."""
        nonlocal maze, anim, anim_maze, gradient, trail, _prev_active_coord, show_solution, solution_anim
        if anim is not None:
            anim.skip()
        maze.close()
        maze = anim_maze
        anim_maze = None
        anim = None
        show_solution = False
        solution_anim = None
        trail.clear()
        _prev_active_coord = None
        _visited_set.clear()
        gradient = generate_gradient(gradient.base)
        renderer.set_gradient(gradient)

    def _cancel_animation() -> None:
        """Esc during animation — discard new maze, restore old interactive maze."""
        nonlocal anim, anim_maze
        if anim_maze is not None:
            anim_maze.close()
        anim_maze = None
        anim = None
        renderer.set_gradient(gradient)

    if args.animate:
        _begin_animation()

    dt: int = 0  # milliseconds since last frame; updated at end of each loop iteration

    try:
        running = True
        while running:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    running = False

                # ---- Menu open: route all input to the menu ----------------
                elif menu_state is not None:
                    if event.type == pygame.KEYDOWN:
                        open_, new_request = menu_state.handle_keydown(event.key)
                        _commit_menu_result(open_, new_request)
                    elif event.type == pygame.KEYUP:
                        open_, new_request = menu_state.handle_keyup(event.key)
                        _commit_menu_result(open_, new_request)
                    elif event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
                        if menu_layout is not None:
                            # Detect arrow-button hold for auto-repeat.
                            _arrow_held = None
                            now = pygame.time.get_ticks()
                            for _sec, _rect in menu_layout.left_arrows.items():
                                if _rect.collidepoint(event.pos):
                                    _arrow_held = (_sec, -1)
                                    _arrow_held_since = now
                                    _arrow_last_fire = now
                                    break
                            if _arrow_held is None:
                                for _sec, _rect in menu_layout.right_arrows.items():
                                    if _rect.collidepoint(event.pos):
                                        _arrow_held = (_sec, +1)
                                        _arrow_held_since = now
                                        _arrow_last_fire = now
                                        break
                            open_, new_request = menu_state.handle_mousedown(event.pos, menu_layout)
                            _commit_menu_result(open_, new_request)
                    elif event.type == pygame.MOUSEBUTTONUP and event.button == 1:
                        _arrow_held = None
                        if menu_layout is not None:
                            open_, new_request = menu_state.handle_mouseup(event.pos, menu_layout)
                            _commit_menu_result(open_, new_request)

                # ---- Animation in progress ---------------------------------
                elif anim is not None:
                    if event.type == pygame.KEYDOWN:
                        if event.key == pygame.K_ESCAPE:
                            _cancel_animation()
                        elif event.key in (pygame.K_SPACE, pygame.K_RETURN, pygame.K_KP_ENTER):
                            _complete_animation()
                        elif event.key == pygame.K_g:
                            animate_mode = not animate_mode
                        elif event.key == pygame.K_h:
                            show_heatmap = not show_heatmap
                        elif event.key == pygame.K_s:
                            show_solution = not show_solution
                    elif event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
                        _complete_animation()

                # ---- Normal gameplay ----------------------------------------
                elif event.type == pygame.KEYDOWN:
                    is_repeat = event.key in keys_held
                    keys_held.add(event.key)
                    if event.key == pygame.K_ESCAPE:
                        if not is_repeat:
                            running = False
                    elif event.key in (pygame.K_SPACE, pygame.K_RETURN, pygame.K_KP_ENTER, pygame.K_n):
                        if not is_repeat and (solved or event.key in (pygame.K_SPACE, pygame.K_n)):
                            solved_btn_pressed = True
                    elif event.key == pygame.K_m:
                        if not is_repeat:
                            solved_btn_pressed = False
                            menu_state = MenuState(
                                request,
                                max_sizes=screen_max_sizes,
                                animate_mode=animate_mode,
                                anim_max_w=ANIM_MAX_W,
                                anim_max_h=ANIM_MAX_H,
                            )
                            menu_layout = None
                            keys_held.clear()
                            pygame.key.set_repeat(300, 60)
                            # Enlarge the window if it's too small to show the
                            # full menu panel, and remember the original size so
                            # we can restore it if the user cancels.
                            pre_menu_size = screen.get_size()
                            need_w = max(screen.get_width(), _MENU_MIN_WINDOW_W)
                            need_h = max(screen.get_height(), _MENU_MIN_WINDOW_H)
                            if (need_w, need_h) != pre_menu_size:
                                screen = pygame.display.set_mode((need_w, need_h))
                            else:
                                pre_menu_size = None  # no resize — nothing to restore
                    elif event.key == pygame.K_g:
                        if not is_repeat:
                            animate_mode = not animate_mode
                    elif event.key == pygame.K_h:
                        if not is_repeat:
                            show_heatmap = not show_heatmap
                    elif event.key == pygame.K_s:
                        if not is_repeat:
                            show_solution = not show_solution
                            if show_solution and anim is None:
                                solution_cells = [c for c in maze.cells() if c.on_solution_path]
                                solution_anim = SolutionAnimState(solution_cells)
                            else:
                                solution_anim = None
                    elif event.key == pygame.K_r:
                        if not is_repeat:
                            solved_btn_pressed = False
                            show_solution = False
                            solution_anim = None
                            if animate_mode:
                                _begin_animation()
                            else:
                                maze.close()
                                maze = Maze(request)
                                gradient = generate_gradient(gradient.base)
                                renderer.set_gradient(gradient)
                                arrows_consumed.clear()
                                drag.end()
                    elif event.key in ARROW_KEYS:
                        if event.key in arrows_consumed:
                            continue
                        keys = pygame.key.get_pressed()
                        direction = _resolve_chord(
                            keys[pygame.K_UP],
                            keys[pygame.K_DOWN],
                            keys[pygame.K_LEFT],
                            keys[pygame.K_RIGHT],
                        )
                        if direction is not None:
                            # Rhombic: open_walls stores diagonal names directly.
                            # Single-arrow cardinals (UP/DOWN/LEFT/RIGHT) don't
                            # match open_walls — remap to the nearest diagonal so
                            # ↑ → UpperRight, → → LowerRight, ↓ → LowerLeft,
                            # ← → UpperLeft.  Diagonal chords (↑+→ etc.) are
                            # already valid and pass through unchanged.
                            if (
                                request.maze_type == MazeType.RHOMBIC
                                and direction not in _RHOMBIC_VALID_DIRECTIONS
                            ):
                                direction = _RHOMBIC_CARDINAL_TO_DIAGONAL[direction]
                            # Delta mazes have no native Left/Right neighbors.
                            # Map the cardinal to the exact horizontal diagonal
                            # for the active cell's orientation so hold-to-move
                            # works reliably (avoids the Rust fallback stalling
                            # on the wrong diagonal after every alternating cell).
                            if (
                                request.maze_type == MazeType.DELTA
                                and direction in (Direction.LEFT, Direction.RIGHT)
                            ):
                                direction = _delta_horizontal(direction, maze.cells())
                            _move_with_slide(maze, direction, request.maze_type)
                            held_arrows = [k for k in ARROW_KEYS if keys[k]]
                            if len(held_arrows) > 1:
                                arrows_consumed.update(held_arrows)
                    elif event.key in key_map:
                        _move_with_slide(maze, key_map[event.key], request.maze_type)
                elif event.type == pygame.KEYUP:
                    keys_held.discard(event.key)
                    if event.key in ARROW_KEYS:
                        arrows_consumed.discard(event.key)
                    if (
                        event.key in (pygame.K_SPACE, pygame.K_RETURN, pygame.K_KP_ENTER, pygame.K_n)
                        and solved_btn_pressed
                    ):
                        solved_btn_pressed = False
                        if animate_mode:
                            _begin_animation()
                        else:
                            maze.close()
                            maze = Maze(request)
                            trail.clear()
                            _prev_active_coord = None
                            _visited_set.clear()
                            gradient = generate_gradient(gradient.base)
                            renderer.set_gradient(gradient)
                            arrows_consumed.clear()
                            drag.end()
                elif event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
                    if solved:
                        solved_btn_pressed = False
                        if animate_mode:
                            _begin_animation()
                        else:
                            maze.close()
                            maze = Maze(request)
                            trail.clear()
                            _prev_active_coord = None
                            _visited_set.clear()
                            gradient = generate_gradient(gradient.base)
                            renderer.set_gradient(gradient)
                            arrows_consumed.clear()
                            drag.end()
                    else:
                        drag.begin(event.pos)
                elif event.type == pygame.MOUSEMOTION:
                    drag.motion(event.pos, maze, cell_size, request.maze_type)
                elif event.type == pygame.MOUSEBUTTONUP and event.button == 1:
                    drag.end()

            # Hold-to-scroll: fire repeated value changes while an arrow button
            # is held, mirroring pygame's key-repeat behaviour for the menu.
            if menu_state is not None and _arrow_held is not None and menu_layout is not None:
                _now = pygame.time.get_ticks()
                if _now - _arrow_held_since >= _MENU_ARROW_REPEAT_DELAY:
                    if _now - _arrow_last_fire >= _MENU_ARROW_REPEAT_INTERVAL:
                        _held_sec, _held_delta = _arrow_held
                        _arrow_map = (
                            menu_layout.left_arrows if _held_delta == -1
                            else menu_layout.right_arrows
                        )
                        if (
                            _held_sec in _arrow_map
                            and _arrow_map[_held_sec].collidepoint(pygame.mouse.get_pos())
                        ):
                            menu_state.section = _held_sec
                            menu_state._change_value(_held_delta)
                        _arrow_last_fire = _now

            # Advance animation with this frame's tick delta.
            if anim is not None:
                if anim.tick(min(dt, 32)):
                    _complete_animation()

            if solution_anim is not None:
                solution_anim.tick(min(dt, 32))

            if anim is not None and anim.steps:
                cells = anim.steps[anim.current_step]
                solved = False
                active_trail = None
            else:
                cells = maze.cells()
                solved = _is_solved(cells)
                active_coord = next((c.coord for c in cells if c.is_active), None)
                if active_coord != _prev_active_coord and _prev_active_coord is not None:
                    if active_coord not in _visited_set:  # new cell — moving forward
                        trail.appendleft(_prev_active_coord)
                    else:                                 # already visited — backtracking
                        trail.clear()
                if active_coord is not None:
                    _visited_set.add(active_coord)
                _prev_active_coord = active_coord
                active_trail = list(trail) if trail else None

            solution_revealed: frozenset | None = (
                solution_anim.revealed_set
                if solution_anim is not None and not solution_anim.done
                else None
            )

            screen.fill((20, 20, 24))
            renderer.draw(cells, show_heatmap=show_heatmap, show_solution=show_solution, trail=active_trail, solution_revealed=solution_revealed)
            if solved:
                _draw_solved_overlay(screen, renderer.maze_rect(cells), big_font, hud_font)

            anim_info: str | None = None
            if anim is not None:
                step = anim.current_step + 1
                total = len(anim.steps)
                anim_info = f"Animating {step}/{total} — Space/click to skip   Esc cancel"
            # Expire transient HUD message if its timer has elapsed.
            _active_hud_msg = _hud_msg if pygame.time.get_ticks() < _hud_msg_until else ""
            _draw_hud(
                screen, hud_font, request, show_heatmap, show_solution, solved,
                animate_mode=animate_mode, anim_info=anim_info, hud_msg=_active_hud_msg,
            )
            if menu_state is not None:
                menu_layout = draw_menu(screen, menu_state, hud_font)

            if solved_btn_pressed:
                gray = pygame.transform.grayscale(screen)
                screen.blit(gray, (0, 0))

            pygame.display.flip()
            dt = clock.tick(60)
    finally:
        maze.close()
        if anim_maze is not None:
            anim_maze.close()
        pygame.quit()


if __name__ == "__main__":
    main()
